name: Unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: [2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2]
        include:
          - os: macos
            ruby: 2.7
          - os: windows
            ruby: 2.4
          - os: windows
            ruby: 2.7
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
             gem install docile          -v 1.3.5  --no-document 
             gem install rtext           -v 0.9.0  --no-document
             gem install rgen            -v 0.8.2  --no-document
             gem install highline        -v 1.7.8  --no-document
             gem install concurrent-ruby -v 1.0.5  --no-document
             gem install thwait          -v 0.1.0  --no-document
             gem install e2mmap          -v 0.1.0  --no-document
             gem install colored         -v 1.2    --no-document
             gem install rspec           -v 3.10.0 --no-document
      - if: ${{matrix.os == 'ubuntu' && matrix.ruby == '2.7'}}
        run: |
             gem install simplecov       -v 0.21.2 --no-document
             gem install simplecov-lcov  -v 0.8.0 --no-document
      - run: rake gh_action_test
      - if: ${{matrix.os == 'ubuntu' && matrix.ruby == '2.7'}}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
